app:
  image: "saksmlz/openresty-testsuite:latest"
  command: "bash"
  container_name: "lua-resty-repl-tests"
  volumes:
    - ".:/lua-resty-repl"
  working_dir: "/lua-resty-repl"

lua51:
  image: "saksmlz/lua51-testsuite:latest"
  command: "sh"
  container_name: "lua-resty-repl-tests"
  volumes:
    - ".:/lua-resty-repl"
  working_dir: "/lua-resty-repl"
